### ISSUE TITLE
Missing Counts

### ISSUE THREAD

**Issue by ljclark** [aelvan/craft-cp-element-count#6]
Since upgrading to 3.1, CP element count has started to not sure on some entries - see screenshot. Some are showing fine, others not (mixture of structures and channels).

Tried clearing CP caches etc, no luck. 

![screenshot 2019-01-15 at 20 48 58](https://user-images.githubusercontent.com/8060816/51209136-73d03080-1907-11e9-9e34-7fb544d2814d.png)

Tried turning a few plugins off that are CP related, and no luck. 

PHP version | 7.1.20
MySQL 5.5.62
Imagick 3.4.3 (ImageMagick 6.8.9-9)
Craft Pro 3.1.0
Yii version 2.0.15.1
Twig version 2.5.0
Guzzle version 6.3.3
Imagine version 0.7-dev

**Comment by janhenckens** [comment]
Got a fix for this, I'll add a PR later today.

**Comment by janhenckens** [comment]
See https://github.com/aelvan/craft-cp-element-count/pull/7

**Comment by aelvan** [comment]
This has been fixes in v1.1.0  thanks to @janhenckens. :)
